### ISSUE TITLE
Commands for extracting

### ISSUE THREAD

**Issue by utdrmac** [Phlogi/tezos-snapshots#1]
Can you please add some docs on how to extract the individual archives?

**Comment by Phlogi** [comment]
Sure, what do you mean by individual archives though? 
The snapshots are simply compressed by xz. So that is all you need. 
The mainnet snapshot is splitted into two files due to the size limitation on github release assets. So make sure you use both files (...xz.00 and ...xz.01). 

What operating system are you on?

**Comment by utdrmac** [comment]
I see it now: `cat mainnet.roll.* | xz -d -v -T0 > mainnet.importme`
I didn't realize that's all you needed to extract the archive parts back into 1.  I've never used xz before.
